# Netlify configuration file for a flattened project structure

[build]
  # This tells Netlify the root directory is the publish directory.
  publish = "calverse-project"
  # The functions directory remains the same.
  functions = "netlify/functions/"

[functions]
  directory = "netlify/functions"
