# Netlify configuration file for a flattened structure

[build]
  # Tell Netlify the root directory is the publish directory.
  publish = "."
  # The functions directory remains the same.
  functions = "netlify/functions/"

[functions]
  directory = "netlify/functions"
