# Netlify configuration file for a project with a 'public' directory

[build]
  # This tells Netlify your published website is in the 'public' directory.
  publish = "public/"
  # This tells Netlify where to find the serverless functions.
  functions = "netlify/functions/"

[functions]
  directory = "netlify/functions"
