# Netlify configuration file

[build]
  # This tells Netlify your published website is in the 'pages' directory.
  publish = "pages/"
  # This tells Netlify where to find the serverless functions.
  functions = "netlify/functions/"
